SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM user_profiles WHERE user_id IN (SELECT id FROM users WHERE role NOT IN ('ADMIN', 'STAFF'));
DELETE FROM users WHERE role NOT IN ('ADMIN', 'STAFF');

DELETE FROM tickets;
DELETE FROM bookings;
DELETE FROM showtimes;
DELETE FROM seats;
DELETE FROM rooms;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO rooms(name, capacity) VALUES ('Phòng 1', 40);
INSERT INTO rooms(name, capacity) VALUES ('Phòng 2', 40);
INSERT INTO rooms(name, capacity) VALUES ('Phòng 3', 40);
INSERT INTO rooms(name, capacity) VALUES ('Phòng 4', 40);
INSERT INTO rooms(name, capacity) VALUES ('Phòng 5', 40);

INSERT INTO seats(room_id, seat_name, seat_number, status)
SELECT r.id, s.seat_name, CAST(SUBSTRING(s.seat_name, 2) AS UNSIGNED), 'AVAILABLE'
FROM rooms r
JOIN (
    SELECT 'A1' AS seat_name UNION ALL SELECT 'A2' UNION ALL SELECT 'A3' UNION ALL SELECT 'A4' UNION ALL SELECT 'A5' UNION ALL SELECT 'A6' UNION ALL SELECT 'A7' UNION ALL SELECT 'A8'
    UNION ALL SELECT 'B1' UNION ALL SELECT 'B2' UNION ALL SELECT 'B3' UNION ALL SELECT 'B4' UNION ALL SELECT 'B5' UNION ALL SELECT 'B6' UNION ALL SELECT 'B7' UNION ALL SELECT 'B8'
    UNION ALL SELECT 'C1' UNION ALL SELECT 'C2' UNION ALL SELECT 'C3' UNION ALL SELECT 'C4' UNION ALL SELECT 'C5' UNION ALL SELECT 'C6' UNION ALL SELECT 'C7' UNION ALL SELECT 'C8'
    UNION ALL SELECT 'D1' UNION ALL SELECT 'D2' UNION ALL SELECT 'D3' UNION ALL SELECT 'D4' UNION ALL SELECT 'D5' UNION ALL SELECT 'D6' UNION ALL SELECT 'D7' UNION ALL SELECT 'D8'
    UNION ALL SELECT 'E1' UNION ALL SELECT 'E2' UNION ALL SELECT 'E3' UNION ALL SELECT 'E4' UNION ALL SELECT 'E5' UNION ALL SELECT 'E6' UNION ALL SELECT 'E7' UNION ALL SELECT 'E8'
) s;
